version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - "3050:3050"
    volumes:
      - ./apps/gateway:/usr/src/app/apps/gateway
      #common files
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - "3040:3040"
    volumes:
      - ./apps/users:/usr/src/app/apps/users
      #common files
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./pnpm-lock.yaml:/usr/src/app/pnpm-lock.yaml
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" #Default port
      - "15672:15672" #Management port
volumes:
  mongodb_data: