version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - "3050:3050"
    volumes:
      - .:/usr/src/app/
    restart: always
    depends_on:
      - users
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: pnpm run start:dev users
    env_file:
      - ./apps/users/.env
    ports:
      - "3040:3040"
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672" #Default port
      - "15672:15672" #Management port
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "5050:3000"
    restart: always
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  mongodb_data:
  grafana_data: